amazon:
  aws:
    accesskey: AKIAXFLBVSBQLWTI2C3G
    region: us-east-2
    secretkey: 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
  dynamodb:
    endpoint: https://dynamodb.us-east-2.amazonaws.com
server:
  port: 8103
spring:
  application:
    name: bids
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - ecs-eth0 #ecs private network
        - veth.*
eureka:
  client:
	service-url:
	  defaultZone: http://eureka-env.eba-znxfshhb.us-east-2.elasticbeanstalk.com:8761/eureka        		    	