package com.cts.fse.eauction.seller.model;

import javax.validation.constraints.Size;
import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "products")
public class Product {

	//Ø Product Name Ø Short Description Ø Detailed Description Ø Category Ø Starting Price Ø Bid end date

	@Size(min = 5, max = 30)
	@DynamoDBAttribute
	private String productName;
	@DynamoDBAttribute
	private String shortDescription;
	@DynamoDBAttribute
	private String detailDescription;
	@DynamoDBAttribute
	private String category;
	@DynamoDBAttribute
	private String startingPrice;
	@DynamoDBAttribute
	private String bidEndDate;
	
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	private Seller seller;
	
		
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Seller getSeller() {
		return seller;
	}
	public void setSeller(Seller seller) {
		this.seller = seller;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public String getShortDescription() {
		return shortDescription;
	}
	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}
	public String getDetailDescription() {
		return detailDescription;
	}
	public void setDetailDescription(String detailDescription) {
		this.detailDescription = detailDescription;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getStartingPrice() {
		return startingPrice;
	}
	public void setStartingPrice(String startingPrice) {
		this.startingPrice = startingPrice;
	}
	public String getBidEndDate() {
		return bidEndDate;
	}
	public void setBidEndDate(String bidEndDate) {
		this.bidEndDate = bidEndDate;
	}
	
	
}
