package com.cts.fse.eauction.buyer.model;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

//@Document
@DynamoDBTable(tableName = "bids")
public class Buyer {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@Size(min = 5, max = 30)
	@NotBlank(message = "First Name is Mandatory")
	@DynamoDBAttribute
	private String firstName;
	@Size(min = 3, max = 25)
	@NotBlank(message = "Last Name is Mandatory")
	@DynamoDBAttribute
	private String lastName;
	@DynamoDBAttribute
	private String address;
	@DynamoDBAttribute
	private String city;
	@DynamoDBAttribute
	private String state;
	@DynamoDBAttribute
	private String pin;
	@DynamoDBAttribute
	private String phoneNumber;
	@Email
	@NotBlank(message = "Email is Mandatory")
	@DynamoDBAttribute
	private String email;
	//Ø Product Id Ø Bid Amount
	@DynamoDBAttribute
	private String productId;
	@DynamoDBAttribute
	private String bidAmount;
	
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public String getProductId() {
		return productId;
	}
	public void setProductId(String productId) {
		this.productId = productId;
	}
	public String getBidAmount() {
		return bidAmount;
	}
	public void setBidAmount(String bidAmount) {
		this.bidAmount = bidAmount;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getPin() {
		return pin;
	}
	public void setPin(String pin) {
		this.pin = pin;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
}
